-- Populate Events
INSERT INTO Event(EVT_TYPE, EVT_NAME, EVT_MONTH, EVT_DAY, EVT_PERIODICITY) VALUES('BIRTHDAY', 'Birthday', 11, 4, 'YEARLY');
INSERT INTO Event(EVT_TYPE, EVT_NAME, EVT_MONTH, EVT_DAY, EVT_PERIODICITY) VALUES('CHRISTMAS', 'Christmas',12, 25, 'YEARLY');
INSERT INTO Event(EVT_TYPE, EVT_NAME, EVT_DATE, EVT_PERIODICITY) VALUES('TRAIL', 'Trail des Passerelles Monteynard', '2019-07-14 08:00:00', 'DATED');