-- Populate Events
INSERT INTO Event(EVT_TYPE, EVT_MONTH, EVT_DAY, EVT_PERIODICITY) VALUES('BIRTHDAY', 11, 4, 'YEARLY');
INSERT INTO Event(EVT_TYPE, EVT_MONTH, EVT_DAY, EVT_PERIODICITY) VALUES('CHRISTMAS', 12, 25, 'YEARLY');